/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.stockmarketinvestinggame;

import java.io.IOException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mankaran
 */
public class HistoricalStockInfo extends javax.swing.JFrame {

    // instance variables
    private InvestGame investGame;
    private String ticker;

    /**
     * Creates new form HistoricalStockInfo
     */
    // contructor
    public HistoricalStockInfo() {
        initComponents();
    }

    // constructor
    public HistoricalStockInfo(InvestGame investGame, String ticker) throws IOException {
        initComponents();
        // initialize instance variables
        this.setResizable(false);
        this.investGame = investGame;
        this.ticker = ticker;

        // store stock history in a list
        List history = this.investGame.getHistory(ticker);
        
        DefaultTableModel historicalDataModel;
        
        historicalDataModel = (DefaultTableModel) this.historicalData.getModel();
        
        // iterate through the list and display the information, each time adding a new row
        for (int i = 0; i < history.size(); i++) {
            String symbolDate = history.get(i).toString().substring(0, 15);
            String lowHigh = history.get(i).toString().substring(17, 37);
            String openClose = history.get(i).toString().substring(40, 61);
            String adjusted = history.get(i).toString().substring(63, history.get(i).toString().length());
            historicalDataModel.addRow(new Object[]{symbolDate, "$" + lowHigh, "$" + openClose, "$" + adjusted});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historicalData = new javax.swing.JTable();

        historicalData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Symbol@Date", "Low-High", "Open->Close", "Adjusted Close"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        historicalData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(historicalData);
        if (historicalData.getColumnModel().getColumnCount() > 0) {
            historicalData.getColumnModel().getColumn(0).setResizable(false);
            historicalData.getColumnModel().getColumn(1).setResizable(false);
            historicalData.getColumnModel().getColumn(2).setResizable(false);
            historicalData.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricalStockInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricalStockInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricalStockInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricalStockInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricalStockInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historicalData;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
